# -*- coding: utf-8 -*-
"""Refresh LIVE snapshot trong docs/CURRENT_STATE.md.

Check git (branch + 5 commit gần + uncommitted), Flask localhost:5055,
bot Telegram getMe. Render markdown vào block <!-- LIVE:BEGIN/END -->.
Chạy manual: python marketing_hub/_scripts/generate_current_state.py
"""
import os, sys, io, re, json, subprocess, datetime
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = Path(__file__).resolve().parent.parent.parent
STATE_FILE = ROOT / 'docs' / 'CURRENT_STATE.md'
FLASK_URL = 'http://localhost:5055/'
HEALTH_TIMEOUT = 5
MARKER_BEGIN = '<!-- LIVE:BEGIN'
MARKER_END = '<!-- LIVE:END -->'


def _git(*args):
    try:
        out = subprocess.check_output(['git', *args], cwd=str(ROOT),
                                       stderr=subprocess.DEVNULL, timeout=10)
        return out.decode('utf-8', errors='replace').strip()
    except (subprocess.SubprocessError, FileNotFoundError) as e:
        return f'[git error: {e}]'


def check_git():
    branch = _git('rev-parse', '--abbrev-ref', 'HEAD')
    log = _git('log', '-5', '--pretty=format:%h %s')
    status = _git('status', '--porcelain')
    modified = sum(1 for ln in status.splitlines() if ln and not ln.startswith('??'))
    untracked = sum(1 for ln in status.splitlines() if ln.startswith('??'))
    return {'branch': branch, 'log': log, 'modified': modified, 'untracked': untracked}


def check_flask():
    try:
        import requests
        r = requests.get(FLASK_URL, timeout=HEALTH_TIMEOUT)
        return {'ok': r.status_code < 500, 'status': r.status_code,
                'latency_ms': int(r.elapsed.total_seconds() * 1000)}
    except Exception as e:
        return {'ok': False, 'error': type(e).__name__}


def _load_telegram_token():
    tok = os.environ.get('TELEGRAM_BOT_TOKEN')
    if tok:
        return tok
    cfg = Path(os.environ.get('USERPROFILE') or Path.home()) / '.openclaw' / 'openclaw.json'
    if cfg.exists():
        try:
            data = json.loads(cfg.read_text(encoding='utf-8'))
            return data.get('channels', {}).get('telegram', {}).get('botToken', '')
        except Exception:
            return ''
    return ''


def check_telegram():
    token = _load_telegram_token()
    if not token:
        return {'ok': False, 'error': 'no_token'}
    try:
        import requests
        r = requests.get(f'https://api.telegram.org/bot{token}/getMe', timeout=HEALTH_TIMEOUT)
        if r.status_code == 200:
            return {'ok': True, 'username': r.json().get('result', {}).get('username', '?')}
        return {'ok': False, 'status': r.status_code, 'desc': r.json().get('description', '')[:80]}
    except Exception as e:
        return {'ok': False, 'error': type(e).__name__}


def render(git, flask, tg):
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    commits = '\n'.join(f'  - `{ln}`' for ln in git['log'].splitlines()) if '\n' in git['log'] or git['log'] else '  - (none)'
    if flask['ok']:
        flask_line = f"🟢 Flask `{FLASK_URL}` — HTTP {flask['status']} ({flask['latency_ms']}ms)"
    else:
        flask_line = f"🔴 Flask `{FLASK_URL}` — {flask.get('error') or 'HTTP '+str(flask.get('status'))}"
    if tg['ok']:
        tg_line = f"🟢 Bot Telegram `@{tg['username']}` — getMe OK"
    elif tg.get('error') == 'no_token':
        tg_line = "🔴 Bot Telegram — token chưa setup"
    else:
        tg_line = f"🔴 Bot Telegram — {tg.get('status','?')} {tg.get('desc','')}".strip()

    return f"""<!-- LIVE:BEGIN — auto-generated by marketing_hub/_scripts/generate_current_state.py — DO NOT EDIT MANUALLY -->
## 🟢 LIVE snapshot (auto-refresh)

_Last run: {now} (GMT+7)_

### Git
- Branch: `{git['branch']}`
- Uncommitted: {git['modified']} modified, {git['untracked']} untracked
- 5 commits gần nhất:
{commits}

### Services
- {flask_line}
- {tg_line}
<!-- LIVE:END -->"""


def main():
    git, flask, tg = check_git(), check_flask(), check_telegram()
    block = render(git, flask, tg)
    text = STATE_FILE.read_text(encoding='utf-8')
    pattern = re.compile(re.escape(MARKER_BEGIN) + r'.*?' + re.escape(MARKER_END), re.DOTALL)
    if not pattern.search(text):
        print(f'[gen_state] LIVE markers not found in {STATE_FILE}', file=sys.stderr)
        sys.exit(1)
    STATE_FILE.write_text(pattern.sub(block, text), encoding='utf-8')
    print(f'[gen_state] Refreshed {STATE_FILE.relative_to(ROOT)}')
    print(block)


if __name__ == '__main__':
    main()
